import {
  Tag,
  Utensils,
  Coffee,
  Pizza,
  Cake,
  IceCream,
  Apple,
  Cherry,
  Salad,
  Sandwich,
  Beer,
  Wine,
  GlassWater,
  ShoppingCart,
  ShoppingBasket,
  ShoppingBag,
  CreditCard,
  Wallet,
  PiggyBank,
  Banknote,
  Landmark,
  BadgeDollarSign,
  Receipt,
  Home,
  Building2,
  Building,
  Warehouse,
  Hotel,
  Bed,
  ShowerHead,
  Lightbulb,
  Bolt,
  Flame,
  Droplet,
  ThermometerSun,
  Fan,
  Car,
  Bus,
  Train,
  TramFront,
  Plane,
  Ship,
  Bike,
  MapPin,
  Compass,
  Fuel,
  Briefcase,
  Laptop,
  Monitor,
  Smartphone,
  Printer,
  Wrench,
  Hammer,
  Paintbrush,
  Heart,
  HeartPulse,
  Stethoscope,
  Pill,
  Shield,
  Dumbbell,
  PersonStanding,
  Sparkles,
  Music,
  Film,
  Gamepad2,
  Ticket,
  BookOpen,
  GraduationCap,
  Gift,
  Baby,
  PawPrint,
  TreePine,
  Flower2,
  Globe,
  BriefcaseBusiness,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  "shopping-basket": ShoppingBasket,
  "shopping-bag": ShoppingBag,
  "credit-card": CreditCard,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  banknote: Banknote,
  landmark: Landmark,
  "badge-dollar-sign": BadgeDollarSign,
  receipt: Receipt,
  home: Home,
  building: Building,
  "building-2": Building2,
  warehouse: Warehouse,
  hotel: Hotel,
  bed: Bed,
  shower: ShowerHead,
  lightbulb: Lightbulb,
  bolt: Bolt,
  flame: Flame,
  droplet: Droplet,
  "thermometer-sun": ThermometerSun,
  fan: Fan,
  car: Car,
  bus: Bus,
  train: Train,
  tram: TramFront,
  plane: Plane,
  ship: Ship,
  bike: Bike,
  "map-pin": MapPin,
  compass: Compass,
  fuel: Fuel,
  briefcase: Briefcase,
  "briefcase-business": BriefcaseBusiness,
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  printer: Printer,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  cake: Cake,
  "ice-cream": IceCream,
  apple: Apple,
  cherry: Cherry,
  salad: Salad,
  sandwich: Sandwich,
  beer: Beer,
  wine: Wine,
  "glass-water": GlassWater,
  heart: Heart,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  shield: Shield,
  dumbbell: Dumbbell,
  "person-standing": PersonStanding,
  sparkles: Sparkles,
  music: Music,
  film: Film,
  gamepad: Gamepad2,
  ticket: Ticket,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  gift: Gift,
  baby: Baby,
  "paw-print": PawPrint,
  "tree-pine": TreePine,
  flower: Flower2,
  globe: Globe,
};

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICON_MAP);

export function getCategoryIcon(key?: string): LucideIcon {
  return CATEGORY_ICON_MAP[key ?? ""] ?? Tag;
}
